/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;


/**
 *
 * @author franc
 */
public class AnimalTela7 extends javax.swing.JFrame {

    boolean verificacao = true;
    /**
     * Creates new form TelaJogo
     */
    public AnimalTela7() {
        initComponents();
        painel.setVisible(false);
        msg_txt.setText("<html>Seu personagem é um <strong>cavalo</strong>?</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao_sim = new javax.swing.JButton();
        botao_nao = new javax.swing.JButton();
        painel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_resposta = new javax.swing.JLabel();
        txt_resposta1 = new javax.swing.JLabel();
        msg_txt = new javax.swing.JLabel();
        balao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icones/teste.png")).getImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao_sim.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botao_sim.setForeground(new java.awt.Color(0, 0, 153));
        botao_sim.setText("Sim");
        botao_sim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_simActionPerformed(evt);
            }
        });
        getContentPane().add(botao_sim, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 136, 60, 30));

        botao_nao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        botao_nao.setForeground(new java.awt.Color(204, 0, 0));
        botao_nao.setText("Não");
        botao_nao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_naoActionPerformed(evt);
            }
        });
        getContentPane().add(botao_nao, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 136, 60, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Seu personagem é: ");

        txt_resposta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_resposta.setForeground(new java.awt.Color(0, 0, 0));
        txt_resposta.setText("<vazio>");

        txt_resposta1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_resposta1.setForeground(new java.awt.Color(0, 0, 0));
        txt_resposta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pulguento.jpg"))); // NOI18N

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_resposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(txt_resposta1)
                .addGap(22, 22, 22))
        );
        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_resposta)))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_resposta1)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 238, -1, 100));
        getContentPane().add(msg_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 150, 70));

        balao.setForeground(new java.awt.Color(0, 0, 0));
        balao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        balao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Balao.png"))); // NOI18N
        getContentPane().add(balao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 340, 160));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/teste.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botao_simActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_simActionPerformed
        
        if (verificacao) {
            Tocando mp3 = new Tocando();
            mp3.sim();

            new TelaPedePano().setVisible(true);
            verificacao = false;
            
        } else {
            JOptionPane.showMessageDialog(null, "Jogue Novamente!");
            this.dispose();
        }
        this.dispose();
    }//GEN-LAST:event_botao_simActionPerformed

    private void botao_naoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_naoActionPerformed
        if (verificacao) {
            Tocando mp3 = new Tocando();
            mp3.nao();

            txt_resposta.setText("Pulguento, Alfinho ou Duffy");
            painel.setVisible(true);
            verificacao = false;
            
        } else {
            JOptionPane.showMessageDialog(null, "Jogue Novamente!");
            this.dispose();
        }
    }//GEN-LAST:event_botao_naoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalTela7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalTela7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalTela7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalTela7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalTela7().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balao;
    private javax.swing.JButton botao_nao;
    private javax.swing.JButton botao_sim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel msg_txt;
    private javax.swing.JPanel painel;
    private javax.swing.JLabel txt_resposta;
    private javax.swing.JLabel txt_resposta1;
    // End of variables declaration//GEN-END:variables
}
